//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuxObjectAuxFlag
    {
        public long AuxObjectFlagId { get; set; }
        public long AuxObjectDataId { get; set; }
        public byte FlagId { get; set; }
    
        public virtual AuxDataFlags AuxDataFlags { get; set; }
        public virtual AuxObjectData AuxObjectData { get; set; }
    }
}
