//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuxObjectData
    {
        public AuxObjectData()
        {
            this.AuxObjectAuxFlag = new HashSet<AuxObjectAuxFlag>();
            this.StciIndexedSubImage = new HashSet<StciIndexedSubImage>();
            this.AuxDataJsdAux = new HashSet<AuxDataJsdAux>();
        }
    
        public long AuxObjectDataId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserId { get; set; }
        public byte WallOrientation { get; set; }
        public byte NumberOfTiles { get; set; }
        public int TileLocIndex { get; set; }
        public byte[] Unused1 { get; set; }
        public byte CurrentFrame { get; set; }
        public byte NumberOfFrames { get; set; }
        public byte[] Unused { get; set; }
    
        public virtual ICollection<AuxObjectAuxFlag> AuxObjectAuxFlag { get; set; }
        public virtual ICollection<StciIndexedSubImage> StciIndexedSubImage { get; set; }
        public virtual ICollection<AuxDataJsdAux> AuxDataJsdAux { get; set; }
    }
}
