//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataType
    {
        public DataType()
        {
            this.FileExtention = new HashSet<FileExtention>();
        }
    
        public int DataTypeId { get; set; }
        public string DataTypeName { get; set; }
        public string Descriotion { get; set; }
    
        public virtual ICollection<FileExtention> FileExtention { get; set; }
    }
}
