//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileExtention
    {
        public int FileExtentionId { get; set; }
        public string Extention { get; set; }
        public int DataTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual DataType DataType { get; set; }
    }
}
