//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ja2DataEntities : DbContext
    {
        public Ja2DataEntities()
            : base("name=Ja2DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuxDataFlags> AuxDataFlags { get; set; }
        public virtual DbSet<AuxObjectAuxFlag> AuxObjectAuxFlag { get; set; }
        public virtual DbSet<AuxObjectData> AuxObjectData { get; set; }
        public virtual DbSet<DataInfo> DataInfo { get; set; }
        public virtual DbSet<FileState> FileState { get; set; }
        public virtual DbSet<JsdArmor> JsdArmor { get; set; }
        public virtual DbSet<JsdAuxData> JsdAuxData { get; set; }
        public virtual DbSet<JsdHeaderFlags> JsdHeaderFlags { get; set; }
        public virtual DbSet<JsdRecordHeaderFlag> JsdRecordHeaderFlag { get; set; }
        public virtual DbSet<JsdStructure> JsdStructure { get; set; }
        public virtual DbSet<JsdStructureFlags> JsdStructureFlags { get; set; }
        public virtual DbSet<JsdTile> JsdTile { get; set; }
        public virtual DbSet<JsdTileFlags> JsdTileFlags { get; set; }
        public virtual DbSet<JsdTileTileFlag> JsdTileTileFlag { get; set; }
        public virtual DbSet<SlfFile> SlfFile { get; set; }
        public virtual DbSet<SlfRecord> SlfRecord { get; set; }
        public virtual DbSet<SlfRecordJsd> SlfRecordJsd { get; set; }
        public virtual DbSet<SlfRecordStci> SlfRecordStci { get; set; }
        public virtual DbSet<StciFlags> StciFlags { get; set; }
        public virtual DbSet<StciIndexed> StciIndexed { get; set; }
        public virtual DbSet<StciIndexedSubImage> StciIndexedSubImage { get; set; }
        public virtual DbSet<StciRecordStciFlag> StciRecordStciFlag { get; set; }
        public virtual DbSet<StciRgb> StciRgb { get; set; }
        public virtual DbSet<UnstructuredData> UnstructuredData { get; set; }
        public virtual DbSet<AuxDataJsdAux> AuxDataJsdAux { get; set; }
        public virtual DbSet<DataType> DataType { get; set; }
        public virtual DbSet<FileExtention> FileExtention { get; set; }
        public virtual DbSet<SlfRecordText> SlfRecordText { get; set; }
        public virtual DbSet<SlfRecordHeader> SlfRecordHeader { get; set; }
        public virtual DbSet<JsdStructureStructureFlag> JsdStructureStructureFlag { get; set; }
        public virtual DbSet<JsdTileCell> JsdTileCell { get; set; }
    }
}
