//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class JsdArmor
    {
        public JsdArmor()
        {
            this.JsdStructure = new HashSet<JsdStructure>();
        }
    
        public byte JsdArmorId { get; set; }
        public string Material { get; set; }
        public byte Value { get; set; }
    
        public virtual ICollection<JsdStructure> JsdStructure { get; set; }
    }
}
