//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class JsdStructure
    {
        public JsdStructure()
        {
            this.JsdTile = new HashSet<JsdTile>();
            this.JsdStructureStructureFlag = new HashSet<JsdStructureStructureFlag>();
        }
    
        public long JsdStructureId { get; set; }
        public long SlfRecordJsdId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserId { get; set; }
        public byte Armour { get; set; }
        public byte HitPoints { get; set; }
        public byte Density { get; set; }
        public byte NumberOfTiles { get; set; }
        public int StructureNumber { get; set; }
        public byte WallOrientation { get; set; }
        public short DestructionPartner { get; set; }
        public short PartnerDelta { get; set; }
        public short ZTileOffsetX { get; set; }
        public short ZTileOffsetY { get; set; }
        public byte Unused { get; set; }
    
        public virtual JsdArmor JsdArmor { get; set; }
        public virtual SlfRecordJsd SlfRecordJsd { get; set; }
        public virtual ICollection<JsdTile> JsdTile { get; set; }
        public virtual ICollection<JsdStructureStructureFlag> JsdStructureStructureFlag { get; set; }
    }
}
