//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class JsdStructureFlags
    {
        public JsdStructureFlags()
        {
            this.JsdStructureStructureFlag = new HashSet<JsdStructureStructureFlag>();
        }
    
        public byte JsdStructureFlagId { get; set; }
        public string Name { get; set; }
        public byte Value { get; set; }
        public Nullable<long> Mask { get; set; }
    
        public virtual ICollection<JsdStructureStructureFlag> JsdStructureStructureFlag { get; set; }
    }
}
