//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class JsdTileCell
    {
        public long JsdTileCellId { get; set; }
        public long JsdTileId { get; set; }
        public byte RowNumber { get; set; }
        public byte CellNumber { get; set; }
        public byte Value { get; set; }
    
        public virtual JsdTile JsdTile { get; set; }
    }
}
