//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class JsdTile
    {
        public JsdTile()
        {
            this.JsdTileTileFlag = new HashSet<JsdTileTileFlag>();
            this.JsdTileCell = new HashSet<JsdTileCell>();
        }
    
        public long JsdTileId { get; set; }
        public long JsdStructureId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserId { get; set; }
        public short PosRelToBase { get; set; }
        public short XPosRelToBase { get; set; }
        public short YPosRelToBase { get; set; }
        public byte VehicleHitLocation { get; set; }
        public byte Unused { get; set; }
    
        public virtual ICollection<JsdTileTileFlag> JsdTileTileFlag { get; set; }
        public virtual JsdStructure JsdStructure { get; set; }
        public virtual ICollection<JsdTileCell> JsdTileCell { get; set; }
    }
}
