//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class JsdTileTileFlag
    {
        public long JsdTileTileFlagId { get; set; }
        public long JsdTileId { get; set; }
        public byte FlagId { get; set; }
    
        public virtual JsdTile JsdTile { get; set; }
        public virtual JsdTileFlags JsdTileFlags { get; set; }
    }
}
