//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlfRecordText
    {
        public long SlfRecordId { get; set; }
        public long SlfRecordHeaderId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserId { get; set; }
        public int SlfFileId { get; set; }
        public string ID { get; set; }
        public string TextData { get; set; }
    
        public virtual SlfFile SlfFile { get; set; }
        public virtual SlfRecordHeader SlfRecordHeader { get; set; }
    }
}
