//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlfRecordJsd
    {
        public SlfRecordJsd()
        {
            this.JsdAuxData = new HashSet<JsdAuxData>();
            this.JsdRecordHeaderFlag = new HashSet<JsdRecordHeaderFlag>();
            this.JsdStructure = new HashSet<JsdStructure>();
        }
    
        public long SlfRecordJsdId { get; set; }
        public long SlfRecordHeaderId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserId { get; set; }
        public int SlfFileId { get; set; }
        public string ID { get; set; }
        public int NumberOfStructuresAndOrImages { get; set; }
        public int NumberOfStructuresStored { get; set; }
        public int StructureDataSize { get; set; }
        public byte[] Unused { get; set; }
        public int NumberOfImageTileLocsStored { get; set; }
    
        public virtual ICollection<JsdAuxData> JsdAuxData { get; set; }
        public virtual ICollection<JsdRecordHeaderFlag> JsdRecordHeaderFlag { get; set; }
        public virtual SlfFile SlfFile { get; set; }
        public virtual ICollection<JsdStructure> JsdStructure { get; set; }
        public virtual SlfRecordHeader SlfRecordHeader { get; set; }
    }
}
