//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class StciFlags
    {
        public StciFlags()
        {
            this.StciRecordStciFlag = new HashSet<StciRecordStciFlag>();
        }
    
        public byte StciFlagsId { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
        public Nullable<int> Mask { get; set; }
    
        public virtual ICollection<StciRecordStciFlag> StciRecordStciFlag { get; set; }
    }
}
