//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class StciIndexed
    {
        public StciIndexed()
        {
            this.StciIndexedSubImage = new HashSet<StciIndexedSubImage>();
        }
    
        public long StciIndexedId { get; set; }
        public long SlfRecordStciId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserId { get; set; }
        public long NumberOfColours { get; set; }
        public int NumberOfSubImages { get; set; }
        public byte RedDepth { get; set; }
        public byte GreenDepth { get; set; }
        public byte BlueDepth { get; set; }
        public byte[] Unused { get; set; }
        public byte[] Palette { get; set; }
    
        public virtual SlfRecordStci SlfRecordStci { get; set; }
        public virtual ICollection<StciIndexedSubImage> StciIndexedSubImage { get; set; }
    }
}
