//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class StciRgb
    {
        public long StciRgbId { get; set; }
        public long SlfRecordStciId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserId { get; set; }
        public int RedMask { get; set; }
        public int GreenMask { get; set; }
        public int BlueMask { get; set; }
        public int AlphaMask { get; set; }
        public byte RedDepth { get; set; }
        public byte GreenDepth { get; set; }
        public byte BlueDepth { get; set; }
        public byte AlphaDepth { get; set; }
        public int UnstructuredDataId { get; set; }
    
        public virtual SlfRecordStci SlfRecordStci { get; set; }
        public virtual UnstructuredData UnstructuredData { get; set; }
    }
}
