//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class StciIndexedSubImage
    {
        public long StciIndexedSubImageId { get; set; }
        public long StciIndexedId { get; set; }
        public Nullable<long> AuxObjectDataId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserId { get; set; }
        public long DataOffset { get; set; }
        public long DataLength { get; set; }
        public int OffsetX { get; set; }
        public int OffsetY { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public int UnstructuredDataId { get; set; }
    
        public virtual AuxObjectData AuxObjectData { get; set; }
        public virtual StciIndexed StciIndexed { get; set; }
        public virtual UnstructuredData UnstructuredData { get; set; }
    }
}
