//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ja2DataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnstructuredData
    {
        public UnstructuredData()
        {
            this.SlfRecord = new HashSet<SlfRecord>();
            this.StciIndexedSubImage = new HashSet<StciIndexedSubImage>();
            this.StciRgb = new HashSet<StciRgb>();
        }
    
        public int UnstructuredDataId { get; set; }
        public byte[] Data { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<SlfRecord> SlfRecord { get; set; }
        public virtual ICollection<StciIndexedSubImage> StciIndexedSubImage { get; set; }
        public virtual ICollection<StciRgb> StciRgb { get; set; }
    }
}
